apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: cjq6rwcds-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/rhtap-qe:a96e48c8ce69c69eae244f360979d3aee652fdb5@sha256:75550b499f19b8d498f040395a1b6ec415437cc0ae756849f2be5ce282b73f75
          name: container-image
