apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: cjq6rwcds-python 
  janus-idp.io/tekton: cjq6rwcds-python
  backstage.io/kubernetes-id: cjq6rwcds-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cjq6rwcds-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  