apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cjq6rwcds-python
  janus-idp.io/tekton: cjq6rwcds-python
  backstage.io/kubernetes-id: cjq6rwcds-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cjq6rwcds-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
