apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cjq6rwcds-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cjq6rwcds-python 
  name: cjq6rwcds-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: cjq6rwcds-python 
